name: CI/CD Pipeline

on:
  push:
    branches:
      - dev   # Trigger on push to dev
      - main  # Trigger on push to main
  pull_request:
    branches:
      - dev   # Trigger on PR to dev
      - main  # Trigger on PR to main

jobs:
  # Job to build Docker image
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t my-app:$GITHUB_SHA .
    
  # Job to deploy (only for main branch)
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # Only run for main branch

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t my-app:$GITHUB_SHA .
        docker push my-app:$GITHUB_SHA

    - name: Run the Docker container on the server (example using SSH)
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker pull my-app:$GITHUB_SHA
          docker run -d --restart always my-app:$GITHUB_SHA
